begin;

insert into public.products (
  type, slug, title, description, is_free, price, warranty, rating,
  sold_count, images, faq, is_published, workflow_link, video_url, updated_at
) values
('chatbot','livestream-chot-don-ai-kich-ban-ban-hang','Livestream Chốt Đơn AI','Tạo kịch bản livestream 30–60 phút, hook mở đầu, demo sản phẩm, xử lý phản đối và câu chốt đơn tự nhiên cho shop Việt.',false,189000,'15 ngày',5.0,0,array['/products/livestream-chot-don-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Tôi nhận được gì?','answer','Một Gem riêng, kịch bản livestream, câu xử lý phản đối và khối sao chép tất cả.'),jsonb_build_object('question','Có bịa giá hoặc khuyến mãi không?','answer','Không. Gem chỉ dùng thông tin bạn cung cấp và đánh dấu phần còn thiếu.')),true,null,null,now()),
('chatbot','ugc-mo-hop-ai-review-san-pham','UGC Mở Hộp AI','Biến ảnh sản phẩm thành concept UGC mở hộp, dùng thử và review chân thật với người Việt Nam và 5 prompt video dọc.',false,169000,'15 ngày',5.0,0,array['/products/ugc-mo-hop-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có giữ đúng bao bì không?','answer','Có, Gem yêu cầu giữ đúng logo, màu sắc, tỷ lệ và chi tiết từ ảnh tham chiếu.')),true,null,null,now()),
('chatbot','salon-toc-kin-lich-ai-video-dat-lich','Salon Tóc Kín Lịch AI','Tạo video kiểu tóc, trải nghiệm salon và nội dung tư vấn giúp khách địa phương tự tin đặt lịch.',false,179000,'15 ngày',5.0,0,array['/products/salon-toc-kin-lich-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Gem có bịa giá salon không?','answer','Không, giá và địa chỉ chỉ xuất hiện khi bạn cung cấp.')),true,null,null,now()),
('chatbot','nha-khoa-tao-niem-tin-ai-video-dat-lich','Nha Khoa Tạo Niềm Tin AI','Xây video nha khoa rõ ràng, có trách nhiệm, giới thiệu quy trình và CTA đặt lịch tư vấn.',false,199000,'15 ngày',5.0,0,array['/products/nha-khoa-tao-niem-tin-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Nội dung có thay thế tư vấn bác sĩ không?','answer','Không. Gem luôn nhắc người xem cần thăm khám trực tiếp và không chẩn đoán cá nhân.')),true,null,null,now()),
('chatbot','studio-cuoi-hut-khach-ai-video-dat-lich','Studio Cưới Hút Khách AI','Tạo concept ảnh cưới, video hậu trường và kịch bản thu hút cặp đôi xem album, nhận tư vấn và đặt lịch.',false,189000,'15 ngày',5.0,0,array['/products/studio-cuoi-hut-khach-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có giữ nhất quán cô dâu chú rể không?','answer','Có, Gem khóa gương mặt, vóc dáng, tóc và trang phục theo từng cảnh.')),true,null,null,now()),
('chatbot','gym-pt-chot-hoi-vien-ai-video-trai-nghiem','Gym PT Chốt Hội Viên AI','Tạo video tập luyện phổ thông, giới thiệu phòng gym và kịch bản chốt lịch trải nghiệm an toàn.',false,179000,'15 ngày',5.0,0,array['/products/gym-pt-chot-hoi-vien-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Gem có hứa giảm cân nhanh không?','answer','Không. Gem tránh cam kết tuyệt đối và không tạo before-after giả.')),true,null,null,now()),
('chatbot','tuyen-dung-hut-ung-vien-ai-video-thuong-hieu','Tuyển Dụng Hút Ứng Viên AI','Biến tin tuyển dụng thành video rõ việc, môi trường, quyền lợi và CTA nhận hồ sơ phù hợp.',false,179000,'15 ngày',5.0,0,array['/products/tuyen-dung-hut-ung-vien-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có dùng được cho nhiều vị trí không?','answer','Có, chỉ cần thay thông tin vị trí, yêu cầu và quyền lợi thực tế.')),true,null,null,now()),
('chatbot','ban-hang-b2b-ai-video-demo-tu-van','Bán Hàng B2B AI','Tạo video demo, kịch bản tư vấn, email theo dõi và câu hỏi khám phá nhu cầu cho sản phẩm doanh nghiệp.',false,199000,'15 ngày',5.0,0,array['/products/ban-hang-b2b-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có bịa thông số hoặc ROI không?','answer','Không. Gem đánh dấu [CẦN BỔ SUNG] khi thiếu thông số, ROI hoặc chứng nhận.')),true,null,null,now()),
('chatbot','dich-vu-tai-nha-ai-video-cho-khach-dia-phuong','Dịch Vụ Tại Nhà AI','Tạo nội dung bán hàng cho vệ sinh, sửa chữa, điện nước và dịch vụ địa phương với CTA gọi hoặc đặt lịch.',false,169000,'15 ngày',5.0,0,array['/products/dich-vu-tai-nha-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có hướng dẫn thao tác nguy hiểm không?','answer','Không. Gem tránh hướng dẫn điện, gas hoặc sửa chữa nguy hiểm cho người không chuyên.')),true,null,null,now()),
('chatbot','khoa-hoc-chot-hoc-vien-ai-video-ban-khoa-hoc','Khóa Học Chốt Học Viên AI','Biến chuyên môn thành chuỗi video giá trị, webinar outline, xử lý phản đối và CTA đăng ký khóa học.',false,189000,'15 ngày',5.0,0,array['/products/khoa-hoc-chot-hoc-vien-ai-cover.png'],jsonb_build_array(jsonb_build_object('question','Có hứa thu nhập hay kết quả tuyệt đối không?','answer','Không. Gem chỉ dùng thành tích và lời chứng thực bạn cung cấp, không phóng đại.')),true,null,null,now())
on conflict (slug) do update set title=excluded.title, description=excluded.description, price=excluded.price, images=excluded.images, faq=excluded.faq, is_published=true, updated_at=now();

insert into public.product_private_content (product_id, workflow_link, video_url, updated_at)
select p.id, x.workflow_link, null, now() from (values
('livestream-chot-don-ai-kich-ban-ban-hang','https://gemini.google.com/gem/d02801c4e9ac'),('ugc-mo-hop-ai-review-san-pham','https://gemini.google.com/gem/bc8173b511fb'),('salon-toc-kin-lich-ai-video-dat-lich','https://gemini.google.com/gem/2f1afe22a7ac'),('nha-khoa-tao-niem-tin-ai-video-dat-lich','https://gemini.google.com/gem/a1788895416f'),('studio-cuoi-hut-khach-ai-video-dat-lich','https://gemini.google.com/gem/14b39492db16'),('gym-pt-chot-hoi-vien-ai-video-trai-nghiem','https://gemini.google.com/gem/f5e109581413'),('tuyen-dung-hut-ung-vien-ai-video-thuong-hieu','https://gemini.google.com/gem/9185db94f988'),('ban-hang-b2b-ai-video-demo-tu-van','https://gemini.google.com/gem/6aa557a22ccc'),('dich-vu-tai-nha-ai-video-cho-khach-dia-phuong','https://gemini.google.com/gem/649b17327c64'),('khoa-hoc-chot-hoc-vien-ai-video-ban-khoa-hoc','https://gemini.google.com/gem/b44a30a8520a')) as x(slug,workflow_link)
join public.products p on p.slug=x.slug
on conflict (product_id) do update set workflow_link=excluded.workflow_link, updated_at=now();

commit;
